title: "Ruoyan Jin"
description: "Enjoy the process."
baseurl: ""   # if this is a user site (ruoyan0103.github.io). 
              # If it's a project site, set baseurl: "/repo-name"
url: "https://ruoyan0103.github.io"

theme: jekyll-theme-slate



